#!/usr/bin/env python3
"""
Standalone script to convert BULGG5100_compiled.csv to HyFI format.

This script reads the Bedretto lab seismic catalog (BULGG5100_compiled.csv) and converts it 
to the format used by HyFI, similar to the SECOS_A18.csv example format.

The conversion includes:
- Event ID generation based on timestamp
- Coordinate transformation (WGS84 to CH1903+ / LV95 using pyproj)
- Time field parsing and formatting
- Mapping of available fields to HyFI format
- Setting default values for missing fields

Usage:
    python convert_BULGG5100_to_HyFI.py

Requirements:
    - pandas
    - numpy
    - pyproj (for coordinate transformation)
    - BULGG5100_compiled.csv file in the same directory

Output:
    - BULGG5100_HyFI_format.csv in HyFI format

Author: Generated by GitHub Copilot
Date: 2025-10-08
"""

import pandas as pd
import numpy as np
from datetime import datetime
import os
try:
    from pyproj import Transformer
    PYPROJ_AVAILABLE = True
except ImportError:
    PYPROJ_AVAILABLE = False
    print("Warning: pyproj not available. Install with: pip install pyproj")
    print("Falling back to approximate coordinate conversion.")

def transform_coordinates(lat, lon, use_pyproj=True):
    """
    Transform coordinates from WGS84 (EPSG:4326) to CH1903+ / LV95 (EPSG:2056)
    
    Args:
        lat (float): Latitude in WGS84
        lon (float): Longitude in WGS84
        use_pyproj (bool): Whether to use pyproj for accurate transformation
        
    Returns:
        tuple: (x, y) coordinates in CH1903+ / LV95 system
    """
    if use_pyproj and PYPROJ_AVAILABLE:
        try:
            # Create transformer from WGS84 to CH1903+ / LV95
            transformer = Transformer.from_crs("EPSG:4326", "EPSG:2056", always_xy=True)
            
            # Transform coordinates (pyproj returns x, y)
            x, y = transformer.transform(lon, lat)
            
            # Basic validation for Swiss coordinates
            # CH1903+ coordinates should be roughly:
            # X (Easting): 2,480,000 - 2,840,000
            # Y (Northing): 1,070,000 - 1,300,000
            if not (2_400_000 <= x <= 2_900_000 and 1_000_000 <= y <= 1_350_000):
                print(f"Warning: Transformed coordinates seem outside Switzerland: X={x:.0f}, Y={y:.0f}")
            
            return x, y
        except Exception as e:
            print(f"Warning: Coordinate transformation failed: {e}")
            print("Falling back to approximate conversion")
            use_pyproj = False
    
def convert_bulgg_to_hyfi(input_file, output_file):
    """
    Convert BULGG5100_compiled.csv to HyFI format similar to SECOS_A18.csv
    
    Args:
        input_file (str): Path to BULGG5100_compiled.csv
        output_file (str): Path for the output HyFI format CSV
    """
    
    print(f"Reading input file: {input_file}")
    
    # Read the BULGG data
    try:
        df = pd.read_csv(input_file)
        print(f"Successfully loaded {len(df)} events from {input_file}")
    except Exception as e:
        print(f"Error reading input file: {e}")
        return False
    
    # Create output dataframe with HyFI format columns
    hyfi_data = []
    
    print("Converting data to HyFI format...")
    
    for idx, row in df.iterrows():
        # Parse datetime from ISO format with improved robustness
        try:
            # First try standard ISO format
            dt = datetime.fromisoformat(row['isotime'].replace('Z', '+00:00'))
        except:
            try:
                # Try parsing with different microsecond precision
                iso_str = row['isotime'].replace('Z', '')
                # Truncate microseconds to 6 digits if longer
                if '.' in iso_str:
                    date_part, frac_part = iso_str.split('.')
                    if len(frac_part) > 6:
                        frac_part = frac_part[:6]
                    iso_str = f"{date_part}.{frac_part}"
                dt = datetime.fromisoformat(iso_str)
            except:
                print(f"Warning: Could not parse datetime for row {idx}: {row['isotime']}")
                continue
            
        # Create event ID based on datetime (similar to SECOS format)
        event_id = f"BED{dt.strftime('%Y%m%d%H%M')}"
        
        depth_km = row['depth']
        
        # Coordinate transformation from WGS84 to CH1903+ / LV95 (EPSG:2056)
        lat = row['latitude']
        lon = row['longitude']
        
        # Transform coordinates using pyproj for accurate conversion
        x_ch1903, y_ch1903 = transform_coordinates(lat, lon, use_pyproj=PYPROJ_AVAILABLE)
        z_depth = depth_km * 1000  # Convert to meters
        
        # Create HyFI format row
        hyfi_row = {
            'ID': event_id,
            'LAT': lat,
            'LON': lon,
            'DEPTH': depth_km,
            'X': x_ch1903,  # CH1903+ X coordinate (Easting) - preserve full precision
            'Y': y_ch1903,  # CH1903+ Y coordinate (Northing) - preserve full precision
            'Z': z_depth,   # Depth in meters - preserve full precision
            'EX': '',  # Not available in BULGG data
            'EY': '',  # Not available in BULGG data
            'EZ': '',  # Not available in BULGG data
            'YR': f'{dt.year}',      # Quoted like in SECOS format
            'MO': f'{dt.month}',     # Quoted like in SECOS format
            'DY': f'{dt.day}',       # Quoted like in SECOS format
            'HR': f'{dt.hour}',      # Quoted like in SECOS format
            'MI': f'{dt.minute}',    # Quoted like in SECOS format
            'SC': dt.second + dt.microsecond / 1e6,  # Include microseconds
            'MAG': row['magnitude'],
            'NCCP': '',  # Not directly available
            'NCCS': '',  # Not directly available
            'NCTP': row['ph_usedP'] if 'ph_usedP' in row and pd.notna(row['ph_usedP']) else '',
            'NCTS': row['ph_usedS'] if 'ph_usedS' in row and pd.notna(row['ph_usedS']) else '',
            'RCC': '',   # Not available in BULGG data
            'RCT': '',   # Not available in BULGG data
            'CID': '',   # Not available in BULGG data
        }
        
        hyfi_data.append(hyfi_row)
        
        # Progress indicator
        if (idx + 1) % 1000 == 0:
            print(f"Processed {idx + 1} events...")
    
    # Create output dataframe
    hyfi_df = pd.DataFrame(hyfi_data)
    
    print(f"Converted {len(hyfi_df)} events to HyFI format")
    
    # Save to CSV
    try:
        hyfi_df.to_csv(output_file, index=False)
        print(f"Successfully saved HyFI format data to: {output_file}")
        print(f"Output file contains {len(hyfi_df)} events")
        return True
    except Exception as e:
        print(f"Error saving output file: {e}")
        return False

def main():
    """Main function to run the conversion"""
    
    # Define file paths
    script_dir = os.path.dirname(os.path.abspath(__file__))
    input_file = os.path.join(script_dir, "BULGG5100_compiled.csv")
    output_file = os.path.join(script_dir, "BULGG5100_HyFI_format.csv")
    
    print("="*60)
    print("BULGG5100 to HyFI Format Converter")
    print("="*60)
    
    if PYPROJ_AVAILABLE:
        print("Using pyproj for accurate WGS84 → CH1903+ / LV95 (EPSG:2056) coordinate transformation")
    else:
        print("Warning: Using approximate coordinate transformation (install pyproj for accuracy)")
        print("To install pyproj: pip install pyproj")
    
    # Check if input file exists
    if not os.path.exists(input_file):
        print(f"Error: Input file not found: {input_file}")
        print("Please ensure BULGG5100_compiled.csv is in the same directory as this script.")
        return
    
    # Run conversion
    success = convert_bulgg_to_hyfi(input_file, output_file)
    
    if success:
        print("\n" + "="*60)
        print("Conversion completed successfully!")
        print(f"Input:  {input_file}")
        print(f"Output: {output_file}")
        print("="*60)
        
        # Display basic statistics
        try:
            df = pd.read_csv(output_file)
            print(f"\nOutput file statistics:")
            print(f"- Total events: {len(df)}")
            print(f"- Magnitude range: {df['MAG'].min():.2f} to {df['MAG'].max():.2f}")
            print(f"- Depth range: {df['DEPTH'].min():.3f} to {df['DEPTH'].max():.3f} km")
            
            # Extract coordinate values (remove quotes)
            x_coords = [float(x.strip('"')) for x in df['X']]
            y_coords = [float(y.strip('"')) for y in df['Y']]
            
            print(f"- X coordinates (CH1903+): {min(x_coords):.0f} to {max(x_coords):.0f}")
            print(f"- Y coordinates (CH1903+): {min(y_coords):.0f} to {max(y_coords):.0f}")
            
            if PYPROJ_AVAILABLE:
                print("- Coordinate system: CH1903+ / LV95 (EPSG:2056) - accurate transformation")
            else:
                print("- Coordinate system: Approximate Swiss coordinates (install pyproj for accuracy)")
                
        except Exception as e:
            print(f"Warning: Could not display statistics: {e}")
    else:
        print("\nConversion failed! Please check the error messages above.")

if __name__ == "__main__":
    main()